---
- src: git+https://bitbucket.org/fquffio/ansible-common.git
  name: common
- src: git+https://bitbucket.org/fquffio/ansible-git.git
  name: git
- src: git+https://bitbucket.org/fquffio/ansible-logrotate.git
  name: logrotate
- src: git+https://bitbucket.org/fquffio/ansible-logstash.git
  name: logstash
- src: git+https://bitbucket.org/fquffio/ansible-mysql.git
  name: mysql
- src: git+https://bitbucket.org/fquffio/ansible-ntp.git
  name: ntp
- src: git+https://github.com/Chialab/ansible-php5.git
  name: php5
